KNOWLEDGE_DOCUMENTS = [
    {
        "id": "alz-001",
        "title": "Alzheimer's Disease: Overview and Pathophysiology",
        "source": "Alzheimer's Association Clinical Guidelines 2024",
        "topic": "alzheimers",
        "content": """Alzheimer's disease (AD) is the most common cause of dementia, accounting for 60–80% of cases. It is characterized by progressive neurodegeneration with hallmark pathological features including amyloid-beta plaques and neurofibrillary tangles composed of hyperphosphorylated tau protein. The disease typically progresses through three stages: preclinical (no symptoms, but brain changes occurring), mild cognitive impairment (MCI) due to AD, and Alzheimer's dementia. Neurodegeneration begins in the entorhinal cortex and hippocampus before spreading to the neocortex. Key risk factors include age (greatest risk factor), family history, APOE-ε4 gene variant, cardiovascular disease, traumatic brain injury, and low educational attainment. Modifiable risk factors account for approximately 40% of dementia cases globally. Current FDA-approved treatments include cholinesterase inhibitors (donepezil, rivastigmine, galantamine) and memantine, which provide symptomatic relief but do not halt disease progression. Lecanemab (Leqembi) and donanemab represent new amyloid-targeting immunotherapies approved for early-stage AD.""",
    },
    {
        "id": "alz-002",
        "title": "Alzheimer's Disease: Early Warning Signs and Diagnosis",
        "source": "NIH National Institute on Aging, 2024",
        "topic": "alzheimers",
        "content": """Early warning signs of Alzheimer's disease include memory loss that disrupts daily life (especially forgetting recently learned information), challenges in planning or solving problems, difficulty completing familiar tasks, confusion with time or place, trouble understanding visual images and spatial relationships, new problems with words in speaking or writing, misplacing things and losing the ability to retrace steps, decreased or poor judgment, withdrawal from work or social activities, and changes in mood and personality. Diagnosis is made through clinical evaluation including cognitive testing (MMSE, MoCA), neuropsychological assessment, brain imaging (MRI, PET scans), and biomarker analysis (CSF amyloid and tau, amyloid PET). Blood-based biomarkers (plasma amyloid-beta 42/40 ratio, phosphorylated tau 217) are emerging as accessible screening tools. Early diagnosis is crucial as it allows individuals to participate in planning, access support, and potentially benefit from treatments effective in early stages. The diagnostic criteria were updated in 2023 by the Alzheimer's Association to be biomarker-based rather than symptom-based.""",
    },
    {
        "id": "mci-001",
        "title": "Mild Cognitive Impairment: Definition, Subtypes, and Progression",
        "source": "Journal of Alzheimer's Disease, 2023",
        "topic": "mci",
        "content": """Mild cognitive impairment (MCI) is an intermediate stage between normal age-related cognitive changes and dementia. Individuals with MCI have cognitive decline greater than expected for their age and education level but do not meet criteria for dementia because daily function remains largely intact. MCI affects approximately 15–20% of adults aged 65 and older. Subtypes include amnestic MCI (memory predominantly affected) and non-amnestic MCI (other cognitive domains affected). Annual conversion rates from MCI to dementia are approximately 10–15%, though some individuals remain stable or even revert to normal cognition. Key biomarkers associated with higher conversion risk include elevated amyloid-beta and tau in CSF, positive amyloid PET, and hippocampal atrophy on MRI. Risk factors for MCI include age, diabetes, high blood pressure, high cholesterol, obesity, depression, lack of physical activity, smoking, and traumatic brain injury. The relationship between sleep disorders and MCI progression is an active area of research, with evidence suggesting that poor sleep accelerates amyloid accumulation.""",
    },
    {
        "id": "mci-002",
        "title": "Prevention Strategies for Cognitive Decline and MCI",
        "source": "Lancet Neurology Commission on Dementia Prevention, 2024",
        "topic": "mci",
        "content": """Evidence-based prevention strategies for cognitive decline target modifiable risk factors. The Lancet Commission identifies 14 modifiable risk factors accounting for approximately 45% of dementia cases: less education, hearing loss, hypertension, obesity, smoking, depression, physical inactivity, diabetes, low social contact, excessive alcohol consumption, traumatic brain injury, air pollution, high LDL cholesterol, and vision loss. Physical exercise is among the strongest evidence-based interventions, with aerobic exercise (150 minutes/week moderate intensity) associated with reduced dementia risk by up to 35%. The MIND diet (Mediterranean-DASH Intervention for Neurodegenerative Delay), combining Mediterranean and DASH dietary patterns emphasizing leafy greens, berries, nuts, fish, and olive oil, is associated with slower cognitive decline. Cognitive engagement through lifelong learning, social interaction, and mentally stimulating activities builds cognitive reserve. Sleep optimization (7–9 hours for adults) is critical as sleep is when the glymphatic system clears amyloid from the brain. Hearing aid use in older adults with hearing loss has shown promise in reducing cognitive decline in randomized controlled trials.""",
    },
    {
        "id": "dep-001",
        "title": "Depression in Older Adults: Cognitive Implications",
        "source": "American Journal of Geriatric Psychiatry, 2024",
        "topic": "depression",
        "content": """Depression is highly prevalent in older adults, affecting approximately 15–20% of community-dwelling adults over 65 and up to 40% in long-term care settings. Depression is both a risk factor for and an early symptom of dementia. Late-life depression (LLD) is associated with cognitive deficits in processing speed, executive function, memory, and attention that may persist even after remission of depressive symptoms. The relationship between depression and dementia is bidirectional—depression increases dementia risk by approximately 65%, and dementia increases depression risk. Proposed mechanisms include increased cortisol from chronic stress damaging hippocampal neurons, inflammatory pathways (elevated IL-6, TNF-alpha, CRP), vascular changes, and reduced BDNF (brain-derived neurotrophic factor). Treatment approaches include selective serotonin reuptake inhibitors (SSRIs, preferred due to tolerability profile in older adults), serotonin-norepinephrine reuptake inhibitors (SNRIs), cognitive-behavioral therapy (CBT), behavioral activation, problem-solving therapy, and exercise. Collaborative care models integrating mental health with primary care show superior outcomes. Electroconvulsive therapy (ECT) remains highly effective for severe or treatment-resistant depression in older adults.""",
    },
    {
        "id": "dep-002",
        "title": "Pseudodementia: Depression Mimicking Cognitive Decline",
        "source": "Psychiatric Clinics of North America, 2023",
        "topic": "depression",
        "content": """Pseudodementia, or depressive pseudodementia, refers to cognitive impairment secondary to depression that mimics dementia. It is common in older adults and is important to distinguish from true neurodegenerative dementia because it is potentially reversible with adequate treatment. Key differentiating features: pseudodementia typically has a more abrupt onset, patients often complain about their memory loss (vs. dementia patients who may be unaware), and cognitive deficits improve with successful depression treatment. Neuropsychological testing typically shows deficits in effortful processing, attention, and processing speed, with relative preservation of memory encoding in pseudodementia. The distinction is clinically important: treating underlying depression can significantly restore cognitive function. However, longitudinal studies show that individuals who experience pseudodementia have a higher subsequent risk of developing true dementia. Brain imaging (particularly FDG-PET and amyloid PET) and CSF biomarkers can help differentiate the conditions when clinical assessment is inconclusive. Comprehensive geriatric assessment integrating cognitive, functional, and psychiatric evaluation is the recommended diagnostic approach.""",
    },
    {
        "id": "anx-001",
        "title": "Anxiety Disorders and Cognitive Function",
        "source": "Neuroscience & Biobehavioral Reviews, 2024",
        "topic": "anxiety",
        "content": """Anxiety disorders are among the most prevalent mental health conditions, affecting approximately 15% of older adults. Common types in older adults include generalized anxiety disorder (GAD), social anxiety disorder, specific phobias, and anxiety secondary to medical conditions. Anxiety significantly impacts cognitive function through multiple pathways: hyperactivation of the hypothalamic-pituitary-adrenal (HPA) axis leads to elevated cortisol, which impairs prefrontal cortex function and hippocampal neurogenesis. Cognitive effects include impaired working memory, reduced executive function, attentional bias toward threats, and difficulties with cognitive flexibility. Chronic anxiety is associated with accelerated cognitive aging and increased risk of MCI and dementia. The amygdala-prefrontal cortex circuit dysregulation central to anxiety disorders also plays a role in memory processing, explaining memory biases in anxious individuals (better recall of threatening than neutral information). Evidence-based treatments include cognitive-behavioral therapy (CBT), acceptance and commitment therapy (ACT), mindfulness-based stress reduction (MBSR), and pharmacotherapy with SSRIs or SNRIs as first-line agents. Benzodiazepines should be avoided in older adults due to cognitive side effects and fall risk.""",
    },
    {
        "id": "anx-002",
        "title": "Generalized Anxiety Disorder in Later Life",
        "source": "Clinical Psychology Review, 2023",
        "topic": "anxiety",
        "content": """Generalized anxiety disorder (GAD) is characterized by persistent, excessive worry about various life circumstances lasting six months or more, accompanied by physical symptoms including restlessness, fatigue, difficulty concentrating, irritability, muscle tension, and sleep disturbance. In older adults, worry content often differs from younger adults, focusing more on health, safety, family, and finances. GAD is frequently comorbid with depression (50% comorbidity rate), and the presence of both conditions is associated with greater functional impairment and poorer outcomes. Late-life GAD presentations may be complicated by medical comorbidities that produce similar symptoms (thyroid disorders, cardiovascular conditions, medication side effects). Assessment tools validated for older adults include the GAD-7, Geriatric Anxiety Inventory (GAI), and Penn State Worry Questionnaire–Abbreviated (PSWQ-A). Cognitive-behavioral therapy adapted for older adults (modifying pacing, using larger print, incorporating reminiscence) demonstrates efficacy equivalent to that in younger adults. Problem-solving therapy and mindfulness-based cognitive therapy (MBCT) also show evidence for late-life GAD. Self-help interventions including progressive muscle relaxation, diaphragmatic breathing, and structured problem-solving provide accessible options.""",
    },
    {
        "id": "int-001",
        "title": "Exercise and Brain Health: Evidence-Based Recommendations",
        "source": "British Journal of Sports Medicine / WHO Guidelines 2024",
        "topic": "interventions",
        "content": """Physical exercise is one of the most robust evidence-based interventions for brain health and cognitive function. Aerobic exercise increases cerebral blood flow, promotes neurogenesis in the hippocampus through BDNF upregulation, reduces neuroinflammation, and improves vascular risk factors. A meta-analysis of 39 studies found aerobic exercise reduces dementia risk by 30–35% in cognitively healthy adults. Resistance training improves executive function, memory, and attention through IGF-1 and BDNF pathways. WHO guidelines recommend at least 150–300 minutes/week of moderate-intensity aerobic physical activity or 75–150 minutes/week of vigorous-intensity activity for adults. For cognitively healthy older adults aiming to reduce dementia risk, emerging evidence supports progressive resistance training 2x/week in addition to aerobic activity. The EXERT trial (2022) found that both high-intensity aerobic exercise and low-intensity stretching/balance exercise for 12 months prevented cognitive decline in MCI, though high-intensity exercise was not superior to low-intensity. Even light physical activity (walking, gardening) is associated with better cognitive outcomes than sedentary behavior. The effect of exercise appears most pronounced when initiated before significant cognitive decline occurs, emphasizing lifelong activity.""",
    },
    {
        "id": "int-002",
        "title": "Sleep and Cognitive Health: The Role of the Glymphatic System",
        "source": "Nature Reviews Neuroscience, 2024",
        "topic": "interventions",
        "content": """Sleep is a critical regulator of brain health, with growing evidence that sleep disturbances contribute to cognitive decline and dementia risk. The glymphatic system, a waste-clearance pathway active primarily during slow-wave sleep, clears amyloid-beta and tau from the brain interstitium. Sleep deprivation leads to acute increases in brain amyloid-beta, and chronic poor sleep is associated with greater amyloid plaque burden on PET imaging. Recommended sleep duration for adults is 7–9 hours; both short sleep (< 6 hours) and long sleep (> 9 hours) are associated with increased dementia risk. Obstructive sleep apnea (OSA), highly prevalent in older adults (30–50%), is independently associated with cognitive impairment and increased amyloid burden; CPAP treatment may partially reverse these effects. Sleep hygiene strategies: maintaining consistent sleep/wake schedule, limiting caffeine after noon, avoiding alcohol near bedtime (disrupts sleep architecture), creating a cool/dark/quiet sleep environment, and limiting screen time before bed. Cognitive-behavioral therapy for insomnia (CBT-I) is the first-line recommended treatment for chronic insomnia, more effective than pharmacotherapy for long-term outcomes. Melatonin (0.5–5 mg) can help with sleep timing but has limited evidence for sleep quality improvement in older adults with primary insomnia.""",
    },
    {
        "id": "int-003",
        "title": "The MIND Diet and Cognitive Health",
        "source": "Alzheimer's & Dementia: The Journal of the Alzheimer's Association, 2023",
        "topic": "interventions",
        "content": """The MIND diet (Mediterranean-DASH Intervention for Neurodegenerative Delay) was developed by nutritional epidemiologist Martha Clare Morris specifically to protect brain health. It emphasizes 10 brain-healthy food groups: green leafy vegetables (6+ servings/week), other vegetables (1+/day), nuts (5+ servings/week), berries (2+ servings/week, particularly blueberries and strawberries), beans (4+ meals/week), whole grains (3+ servings/day), fish (1+ serving/week), poultry (2+ servings/week), olive oil (primary oil used), and wine (1 glass/day optional). Foods to limit: red meat (<4 servings/week), butter/margarine (<1 tablespoon/day), cheese (<1 serving/week), pastries/sweets (<5 servings/week), and fried/fast food (<1 serving/week). In the original MIND diet study, high adherence was associated with 53% lower rate of Alzheimer's disease and slower cognitive decline equivalent to being 7.5 years younger cognitively. Key neuroprotective mechanisms include antioxidant and anti-inflammatory effects (flavonoids in berries, omega-3 fatty acids in fish, monounsaturated fats in olive oil), reduction of vascular risk factors, and support for gut-brain axis through dietary fiber. The MIND-ADMCI trial randomized 604 participants at risk for dementia and found MIND diet significantly slowed cognitive decline over 3 years.""",
    },
    {
        "id": "care-001",
        "title": "Dementia Caregiving: Strategies and Self-Care",
        "source": "Alzheimer's Association Caregiver Resources, 2024",
        "topic": "caregiving",
        "content": """Approximately 11 million Americans provide unpaid care for people with Alzheimer's or other dementias. Caregiving can be physically, emotionally, and financially demanding, with caregivers experiencing higher rates of depression (up to 50%), anxiety, sleep problems, and immune dysfunction compared to non-caregivers. The stress-health model of caregiving (Pearlin, 1990) identifies primary stressors (care demands, problem behaviors) and secondary stressors (work-family conflicts, financial strain) that drive caregiver outcomes. Evidence-based strategies for managing behavioral and psychological symptoms of dementia (BPSD) include: Validating emotions rather than correcting misperceptions. Using simple, short sentences and maintaining eye contact. Establishing consistent routines to reduce confusion. Redirecting to pleasant activities when distress occurs. Adapting the environment to enhance safety and independence (nightlights, door alarms, simplified spaces). Caregiver support resources include: Alzheimer's Association 24/7 Helpline (1-800-272-3900), local caregiver support groups, adult day programs, respite care services, and the REACH II (Resources for Enhancing Alzheimer's Caregiver Health) program, an evidence-based intervention showing significant reduction in caregiver burden and depression. Legal and financial planning (power of attorney, advance directives, Medicaid planning) should be addressed early in the disease course while the person with dementia can participate.""",
    },
    {
        "id": "care-002",
        "title": "Communication Strategies in Dementia Care",
        "source": "Journal of Gerontological Nursing, 2023",
        "topic": "caregiving",
        "content": """Effective communication is one of the most important skills for dementia caregivers. As the disease progresses, verbal communication abilities decline, requiring adaptation to the person's changing abilities. Key communication principles: Approach from the front at eye level to avoid startling. Use the person's preferred name and identify yourself. Speak slowly and clearly using simple sentences. Ask one question at a time using yes/no questions when possible. Allow ample time for response (30+ seconds). Use nonverbal communication—gentle touch, facial expressions, and tone of voice become increasingly important as verbal language declines. Person-centered communication approaches focus on the emotional reality of the person with dementia rather than on cognitive accuracy. Reminiscence therapy—discussing past memories using photos, music, and familiar objects—can provide meaningful engagement and reduce agitation. Music therapy leverages preserved musical memory networks (limbic system) that remain relatively intact longer than other memory systems. Validation therapy, developed by Naomi Feil, acknowledges and validates the emotional content of communications even when the factual content may not be accurate. Environmental communication supports include visual cues (labeled drawers, picture schedules), contrasting colors for improved spatial navigation, and reduction of background noise and visual clutter.""",
    },
    {
        "id": "brain-001",
        "title": "Normal Cognitive Aging vs. Pathological Cognitive Decline",
        "source": "Current Opinion in Neurology, 2024",
        "topic": "brain_health",
        "content": """Normal cognitive aging is characterized by gradual, modest changes in certain cognitive domains while others remain relatively preserved. Processing speed typically begins declining in the 20s–30s and continues throughout life. Episodic memory (remembering specific events) shows age-related decline, particularly in recall (vs. recognition, which is more preserved). Working memory capacity decreases modestly with age. However, crystallized intelligence (accumulated knowledge, vocabulary, general fund of information) remains stable or even improves through the 60s–70s. Pathological cognitive decline differs from normal aging in: Rate of change (faster than expected for age), breadth (multiple domains affected), severity (interfering with daily function), and associated biomarkers (amyloid, tau, neurodegeneration). Subjective cognitive decline (SCD)—when individuals perceive memory changes without objective test abnormalities—may represent the earliest detectable stage of AD in some cases. Key factors that protect cognitive reserve and delay clinical symptom onset include: educational attainment, occupational complexity, bilingualism, social engagement, and physical and cognitive activity across the lifespan. Cognitive reserve does not prevent brain pathology but allows individuals to tolerate more pathology before clinical symptoms emerge. Neuroplasticity—the brain's ability to form new connections and adapt—persists throughout life, supporting the rationale for cognitive interventions in older adults.""",
    },
    {
        "id": "brain-002",
        "title": "Cognitive Training and Brain Stimulation in Older Adults",
        "source": "Psychological Science in the Public Interest, 2024",
        "topic": "brain_health",
        "content": """Cognitive training refers to structured programs targeting specific cognitive abilities through repeated practice. Evidence on transfer effects (gains spreading beyond trained tasks to real-world function) remains debated. The ACTIVE trial (Advanced Cognitive Training for Independent and Vital Elderly), the largest RCT of cognitive training, demonstrated that 10 sessions of training in speed of processing, memory strategy, or reasoning produced domain-specific improvements persisting 10 years, with speed-of-processing training associated with reduced dementia incidence (by 29% in most recent analysis). Commercially available brain training programs show near-transfer within trained tasks but limited far-transfer to untrained tasks or daily activities. Integrated cognitive training programs combining cognitive exercises with physical activity may show superior effects to either alone. Non-invasive brain stimulation techniques under investigation include: transcranial direct current stimulation (tDCS)—applying weak electrical currents to modulate cortical excitability; transcranial magnetic stimulation (TMS)—using magnetic fields to stimulate specific brain regions; and photobiomodulation—using near-infrared light. These approaches show promise in early clinical trials but are not yet established clinical treatments. For daily practice, activities associated with cognitive benefits include learning new skills (instrument, language, art), engaging social activities, challenging reading and games (specifically those requiring active engagement, problem-solving, and learning).""",
    },
    {
        "id": "neuro-001",
        "title": "Vascular Cognitive Impairment and Dementia",
        "source": "Stroke, American Heart Association/American Stroke Association, 2024",
        "topic": "brain_health",
        "content": """Vascular cognitive impairment (VCI) encompasses cognitive disorders caused by cerebrovascular disease, ranging from mild vascular cognitive impairment to vascular dementia (VaD). VaD is the second most common cause of dementia after Alzheimer's disease, accounting for 15–20% of dementia cases, though mixed pathology (vascular + Alzheimer's) is more prevalent than pure VaD. Cerebrovascular mechanisms include: large vessel disease (strategic infarcts in regions critical for cognition—hippocampus, thalamus, caudate), small vessel disease (white matter lesions, lacunar infarcts, cerebral microbleeds), and global hypoperfusion. Cognitive profile: executive dysfunction and processing speed are typically more impaired than memory, in contrast to AD where memory is disproportionately affected. Stepped or abrupt cognitive decline rather than gradual progression may suggest vascular etiology. Prevention is the primary strategy: blood pressure control (target < 130/80 mmHg per current guidelines) is the most important modifiable factor, with antihypertensive treatment reducing dementia risk by 12–16%. Additional cardiovascular risk factor management includes: diabetes control (HbA1c target < 7%), lipid management (statins), anticoagulation for atrial fibrillation, smoking cessation, and physical activity. Post-stroke cognitive monitoring and rehabilitation are recommended given that 1 in 3 stroke survivors develops post-stroke dementia.""",
    },
]

TOPIC_CATEGORIES = [
    {
        "id": "alzheimers",
        "name": "Alzheimer's Disease",
        "description": "Pathophysiology, diagnosis, treatments, and stages of Alzheimer's disease",
        "icon": "🧠",
        "document_count": len([d for d in KNOWLEDGE_DOCUMENTS if d["topic"] == "alzheimers"]),
    },
    {
        "id": "mci",
        "name": "Mild Cognitive Impairment",
        "description": "MCI subtypes, risk factors, prevention strategies, and biomarkers",
        "icon": "🔍",
        "document_count": len([d for d in KNOWLEDGE_DOCUMENTS if d["topic"] == "mci"]),
    },
    {
        "id": "depression",
        "name": "Depression & Cognition",
        "description": "Late-life depression, pseudodementia, and cognitive implications",
        "icon": "💙",
        "document_count": len([d for d in KNOWLEDGE_DOCUMENTS if d["topic"] == "depression"]),
    },
    {
        "id": "anxiety",
        "name": "Anxiety Disorders",
        "description": "Anxiety types, cognitive effects, and evidence-based treatments",
        "icon": "🌿",
        "document_count": len([d for d in KNOWLEDGE_DOCUMENTS if d["topic"] == "anxiety"]),
    },
    {
        "id": "interventions",
        "name": "Cognitive Interventions",
        "description": "Exercise, sleep, diet, and evidence-based prevention strategies",
        "icon": "✅",
        "document_count": len([d for d in KNOWLEDGE_DOCUMENTS if d["topic"] == "interventions"]),
    },
    {
        "id": "caregiving",
        "name": "Dementia Caregiving",
        "description": "Caregiver strategies, communication, and support resources",
        "icon": "🤝",
        "document_count": len([d for d in KNOWLEDGE_DOCUMENTS if d["topic"] == "caregiving"]),
    },
    {
        "id": "brain_health",
        "name": "Brain Health & Aging",
        "description": "Normal aging, cognitive reserve, and vascular cognitive health",
        "icon": "⚡",
        "document_count": len([d for d in KNOWLEDGE_DOCUMENTS if d["topic"] == "brain_health"]),
    },
]
